table Region

	column 'Region Key'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: region_key

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: region

	partition Region = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\dim_region.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"region_key", type text}, {"region", type text}}, "en-US")
				in
				    Typed
