table 'User Region'
	isHidden

	column 'User Email'
		dataType: string
		summarizeBy: none
		sourceColumn: user_email

	column 'Region Key'
		dataType: string
		summarizeBy: none
		sourceColumn: region_key

	partition 'User Region' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\dim_user_region.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"user_email", type text}, {"region_key", type text}}, "en-US")
				in
				    Typed
